{% set version = "1.2.1" %}

package:
  name: rnabloom
  version: '{{ version }}'

source:
  url: https://github.com/bcgsc/RNA-Bloom/releases/download/v{{ version }}/rnabloom_v1.2.1.tar.gz

build:
  noarch: generic
  number: 0

requirements:
  run:
    - openjdk >=8

test:
  commands:
    - "bash -c 'rnabloom --version'"

about:
  home: https://github.com/bcgsc/RNA-Bloom
  license: GPLv3
  license_family: GPL
   license_file: LICENSE
  summary: Java tool for RNA-seq assembly
  description: >- 
    RNA-Bloom is a lightweight transcriptome assembly tool for short-reads and
    nanopore reads.
  dev_url: https://github.com/bcgsc/RNA-Bloom
  doc_url: https://github.com/bcgsc/RNA-Bloom/blob/master/README.md